""" 定数 """
COOKING_CATEGORY_MAIN   = "主菜"
COOKING_CATEGORY_SUB    = "副菜"
COOKING_CATEGORY_SOUP   = "汁物"
COOKING_CATEGORY_DESERT = "デザート"
COOKING_CATEGORY_LIST   = {
    "main"  : COOKING_CATEGORY_MAIN,
    "sub"   : COOKING_CATEGORY_SUB,
    "soup"  : COOKING_CATEGORY_SOUP,
    "desert": COOKING_CATEGORY_DESERT,
}
SCRAPING_COUNT = 30
SCRAPING_SLEEP = 0
SUCCESS = True
FAILED = False
ADD = True
DELETE = False