# Generated by Django 4.2.2 on 2024-08-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='detail',
            field=models.TextField(),
        ),
    ]
