# Generated by Django 4.2.2 on 2024-08-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_alter_instruction_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='memo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
