# Generated by Django 4.2.2 on 2024-08-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_author_cookingcategory_ingredientname_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='order',
            field=models.IntegerField(),
        ),
    ]
