# Generated by Django 4.2.2 on 2024-08-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_alter_instruction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='servings',
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
