# Generated by Django 4.2.2 on 2024-08-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_alter_instruction_detail_alter_instruction_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
