# Generated by Django 4.2.2 on 2024-08-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_alter_ingredients_amount_alter_instruction_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite_flg',
            field=models.BooleanField(default=True),
        ),
    ]
