# Generated by Django 4.2.2 on 2024-08-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_favorite_favorite_flg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite_flg',
            field=models.BooleanField(default=False),
        ),
    ]
