# Generated by Django 4.2.2 on 2024-08-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_alter_favorite_favorite_flg'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('custom_user', 'recipe')},
        ),
    ]
